---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 李现.
--- DateTime: 2026/7/5 23:41
---

-- KEYS[1]: 限流 key
-- ARGV[1]: 窗口大小（毫秒）
-- ARGV[2]: 窗口内最大请求数
-- ARGV[3]: 当前时间戳（毫秒）
-- ARGV[4]: 唯一标识

local key = KEYS[1]
local window = tonumber(ARGV[1])
local limit = tonumber(ARGV[2])
local now = tonumber(ARGV[3])
local unique = ARGV[4]

-- 清理窗口外的请求记录
redis.call('ZREMRANGEBYSCORE', key, 0, now - window)

-- 统计当前窗口内请求数
local count = redis.call('ZCARD', key)

if count >= limit then
    return 0
end

-- 记录当前请求
redis.call('ZADD', key, now, unique)
redis.call('PEXPIRE', key, window)

return 1