---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 李现.
--- DateTime: 2026/7/3 0:08
---

-- KEYS[1] = 库存 key (product:stock:{productId})
-- ARGV[1] = 回滚数量
redis.call('INCRBY', KEYS[1], ARGV[1])
return 1