---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 李现.
--- DateTime: 2026/7/3 0:01
---
-- KEYS[1] = 库存 key (product:stock:{productId})
-- ARGV[1] = 扣减数量
-- 返回 1=成功 0=库存不足

-- 第 1 步：读
local stock = redis.call('GET',KEYS[1])

-- 第 2 步：判断
if not stock or tonumber(stock) < tonumber(ARGV[1]) then
    return 0        -- 不够，返回失败
end

-- 第 3 步：写
redis.call('DECRBY',KEYS[1],ARGV[1])
return 1          -- 扣成功
